#! /bin/bash
set -e 

echo "
------------------------------------------------------------------------
------------------------------------------------------------------------
-------------                Building              ---------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
"

composeFile=docker/docker-compose.yml

docker-compose -f $composeFile build
listImages=($(sed -nr 's/image: *(.+)/\1/p' $composeFile))

testFail=0

echo "
------------------------------------------------------------------------
------------------------------------------------------------------------
-------------              Test running            ---------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
"

IFS=""
for imageTag in ${listImages[@]}
do
    if docker run --rm --entrypoint=testDeps "$imageTag" > /dev/null ; then
        echo "TEST PASS: '${imageTag}'"
    else
        testFail=1
        echo "TEST FAIL: '${imageTag}'"
    fi
done

if [[ "$testFail" == "1" ]]; then
    exit 1
fi

docker-compose -f $composeFile  push