version: '3.3'

services:
  base:
    build: ./56-apache-base
    image: silmaralberti/php:5.6-apache-base
  dev:
    build: ./56-apache-dev
    image: silmaralberti/php:5.6-apache-dev
  base7:
    build: ./72-apache-base
    image: silmaralberti/php:7.2-apache-base
  dev7:
    build: ./72-apache-dev
    image: silmaralberti/php:7.2-apache-dev
  prod7:
    build: ./72-apache-prod
    image: silmaralberti/php:7.2-apache-prod
