version: '3.3'

services:
  base5:
    build: 
      context: .
      dockerfile: ./56-apache-base/Dockerfile
    image: silmaralberti/php:5.6-apache-base
  dev5:
    build: 
      context: .
      dockerfile: ./56-apache-dev/Dockerfile
    image: silmaralberti/php:5.6-apache-dev
  base7:
    build: 
      context: .
      dockerfile: ./72-apache-base/Dockerfile
    image: silmaralberti/php:7.2-apache-base
  dev7:
    build: 
      context: .
      dockerfile: ./72-apache-dev/Dockerfile
    image: silmaralberti/php:7.2-apache-dev
  base74:
    build: 
      context: .
      dockerfile: ./74-apache-base/Dockerfile
    image: silmaralberti/php:7.4-apache-base
  dev74:
    build: 
      context: .
      dockerfile: ./74-apache-dev/Dockerfile
    image: silmaralberti/php:7.4-apache-dev
  prod7:
    build: 
      context: .
      dockerfile: ./72-apache-prod/Dockerfile
    image: silmaralberti/php:7.2-apache-prod
  imagick7:
    build: 
      context: .
      dockerfile: ./72-apache-imagick/Dockerfile
    image: silmaralberti/php:7.2-apache-imagick

