version: "3"

services:
    apache-php5:
        image: silmaralberti/php:5.6-apache-dev
        restart: always
        ports:
            - 80
        volumes:
            - /tmp/profiler:/tmp/profiler
            - /var/www:/var/www
            - ./php56-sites-enabled:/etc/apache2/sites-enabled
            - ./custom.ini:/usr/local/etc/php/conf.d/custom.ini
        environment:
            - HOST_DOCKER_INTERNAL=${HOST_DOCKER_INTERNAL}
            - VIRTUAL_HOST=*.php5.localhost.com
            - VIRTUAL_PORT=80
            - VIRTUAL_PROTO=http

    apache-php7:
        image: silmaralberti/php:7.2-apache-dev
        restart: always
        ports:
            - 80
        volumes:
            - /tmp/profiler:/tmp/profiler
            - /var/www:/var/www
            - ./php72-sites-enabled:/etc/apache2/sites-enabled
            - ./custom.ini:/usr/local/etc/php/conf.d/custom.ini
        environment:
            - HOST_DOCKER_INTERNAL=${HOST_DOCKER_INTERNAL}
            - VIRTUAL_HOST=*.php7.localhost.com
            - VIRTUAL_PORT=80
            - VIRTUAL_PROTO=http

    nginx-proxy:
        container_name: nginx-proxy
        restart: always
        image: jwilder/nginx-proxy
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./config.conf:/etc/nginx/conf.d/config.conf
        environment:
            - TZ=America/Sao_Paulo

