version: "3"

services:
  apache-php5:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.php5.rule=HostRegexp(`php5.localhost.com`, `{subdomain:[a-z0-9]+}.php5.localhost.com`)"
      - "traefik.http.routers.php5.entrypoints=web"
    image: silmaralberti/php:5.6-apache-dev
    restart: unless-stopped
    ports:
      - 80
    volumes:
      - /tmp/profiler:/tmp/profiler
      - /var/www:/var/www
      - ./php56-sites-enabled:/etc/apache2/sites-enabled
      - ./custom.ini:/usr/local/etc/php/conf.d/zz-custom.ini

    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - deploy-ingress

  apache-php7:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.php72.rule=HostRegexp(`php72.localhost.com`, `{subdomain:[a-z0-9]+}.php72.localhost.com`)"
      - "traefik.http.routers.php72.entrypoints=web"
      - "traefik.http.routers.php-auryn.rule=HostRegexp(`photobookfinal.com`, `{subdomain:[a-z0-9]+}.photobookfinal.com`)"
      - "traefik.http.routers.php-auryn.entrypoints=web"
    image: silmaralberti/php:7.2-apache-dev
    restart: unless-stopped
    ports:
      - 80
    volumes:
      - /tmp/profiler:/tmp/profiler
      - /var/www:/var/www
      - ./php72-sites-enabled:/etc/apache2/sites-enabled
      - ./custom.ini:/usr/local/etc/php/conf.d/zz-custom.ini
  
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      deploy-ingress:
        
  apache-php74:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.php74.rule=HostRegexp(`php74.localhost.com`, `{subdomain:[a-z0-9]+}.php74.localhost.com`)"
      - "traefik.http.routers.php74.entrypoints=web"
    image: silmaralberti/php:7.4-apache-dev
    restart: unless-stopped
    ports:
      - 80
    volumes:
      - /tmp/profiler:/tmp/profiler
      - /var/www:/var/www
      - ./php74-sites-enabled:/etc/apache2/sites-enabled
      - ./custom.ini:/usr/local/etc/php/conf.d/zz-custom.ini
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      deploy-ingress:

  apache-php80:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.php80.rule=HostRegexp(`php80.localhost.com`, `{subdomain:[a-z0-9]+}.php80.localhost.com`)"
      - "traefik.http.routers.php80.entrypoints=web"
    image: silmaralberti/php:8.0-apache-dev
    restart: unless-stopped
    ports:
      - 80
    volumes:
      - /tmp/profiler:/tmp/profiler
      - /var/www:/var/www
      - ./php80-sites-enabled:/etc/apache2/sites-enabled
      - ./custom.ini:/usr/local/etc/php/conf.d/zz-custom.ini
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      deploy-ingress:

  apache-php81:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.php81.rule=HostRegexp(`php81.localhost.com`, `{subdomain:[a-z0-9]+}.php81.localhost.com`)"
      - "traefik.http.routers.php81.entrypoints=web"
    image: silmaralberti/php:8.1-apache-dev
    restart: unless-stopped
    ports:
      - 80
    volumes:
      - /tmp/profiler:/tmp/profiler
      - /var/www:/var/www
      - ./php81-sites-enabled:/etc/apache2/sites-enabled
      - ./custom.ini:/usr/local/etc/php/conf.d/zz-custom.ini
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      deploy-ingress:

  traefik:
    image: "traefik:v2.3"
    container_name: "traefik"
    restart: unless-stopped
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.webs.address=:443"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - deploy-ingress

  phpmyadmin:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.localhost.com`)"
      - "traefik.http.routers.phpmyadmin.entrypoints=web"
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-dev
    restart: unless-stopped
    environment:
      PMA_ARBITRARY: 0
      PMA_HOST: database
    ports:
      - 80
    networks:
      - deploy-ingress

  database:
    image: mariadb
    container_name: mariadb-deploy
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "defaultDb"
      # # So you don't have to use root, but you can if you like
      MYSQL_USER: "defaultDb"
      # You can use whatever password you like
      MYSQL_PASSWORD: "root"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - "banco_mysql_deploy:/var/lib/mysql"
      - "./mysql.d/devconf.cnf:/etc/mysql/conf.d/mysql.cnf"
    ports:
      - 3306
      - 3306:3306
    networks:
      - deploy-ingress

volumes:
  banco_mysql_deploy:

networks:
  deploy-ingress:
    driver: bridge
