#!/bin/bash
name='composer-'$(date | md5sum | awk '{print $1}')
eval $(ssh-agent); \
  docker run --rm --interactive --tty \
  --name $name \
  --volume $PWD:/app \
  --volume $HOME/composerHome:$HOME \
  --volume $SSH_AUTH_SOCK:/ssh-auth.sock \
  --volume /etc/passwd:/etc/passwd:ro \
  --volume /etc/group:/etc/group:ro \
  --env SSH_AUTH_SOCK=/ssh-auth.sock \
  --user $(id -u):$(id -g) \
  --network host \
  composer "$@" 
