#!/bin/bash 
name=$(date | md5sum | awk '{print "php56-cli-"$1}')

COMMAND="php $@"
USE_TTY=""
if [[ "$1" == "bash" ]]; then
    COMMAND="bash"
    USE_TTY="t"
fi

docker run -i${USE_TTY} --rm --name $name \
  -v "$PWD":"$PWD" \
  -w $PWD \
  -e XDEBUG_CONFIG="${XDEBUG_CONFIG}" \
  -e XDEBUG_SESSION_START="${XDEBUG_SESSION_START}" \
  --network "host" \
  --add-host=host.docker.internal:host-gateway \
  silmaralberti/php:5.6-apache-dev $COMMAND
