#!/bin/bash 
name=$(date | md5sum | awk '{print "php56-cli-"$1}')
docker run -it --rm --name $name \
  -v "$PWD":"$PWD" \
  -w $PWD \
  -e HOST_DOCKER_INTERNAL=$(hostname -I | awk '{print $1}') \
  -e XDEBUG_CONFIG="remote_enable=1 remote_mode=req remote_port=9000 remote_host=host.docker.internal xdebug.remote_connect_back=0" \
  -e XDEBUG_SESSION_START="start" \
  --network "host" \
  silmaralberti/php:5.6-apache-dev php "$@"