#!/bin/bash

HOST=$(hostname -I 2>/dev/null | awk '{print $1}')
CMD_HOST=""
if [[ $HOST ]]; then
    CMD_HOST="--add-host=host.docker.internal:$HOST"
fi

COMMAND="php $@"
USE_TTY=""
if [[ "$1" == "bash" ]]; then
    COMMAND='bash'
    USE_TTY="t"
fi

name=$(date | md5sum | awk '{print "php72-cli-"$1}')
docker run -i$USE_TTY --rm --name $name \
    -v "$PWD":"$PWD" \
    -w $PWD \
    -e XDEBUG_CONFIG="${XDEBUG_CONFIG}" \
    -e XDEBUG_SESSION_START="${XDEBUG_SESSION_START}" \
    --network "host" \
    $CMD_HOST \
    silmaralberti/php:7.2-apache-dev $COMMAND
