#!/bin/bash 

COMMAND="php $@"
USE_TTY=""
if [[ "$1" == "bash" ]]; then
    COMMAND="bash"
    USE_TTY="t"
fi

name=$(date | md5sum | awk '{print "php72-cli-"$1}')
docker run -i$USE_TTY --rm --name $name \
  -v "$PWD":"$PWD" \
  -w $PWD \
  -e XDEBUG_CONFIG="${XDEBUG_CONFIG}" \
  -e XDEBUG_SESSION_START="${XDEBUG_SESSION_START}" \
  --network "host" \
  --add-host=host.docker.internal:host-gateway \
  silmaralberti/php:8.1-apache-dev $COMMAND
